name: Generate Static Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Run hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create static directory
        run: mkdir -p static

      - name: Generate static pages
        run: python .github/scripts/generate_pages.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "01@0101010101.com"
          git config --local user.name "Jiyong Youn"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update static pages"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}