name: 웹캠 링크 업데이트

on:
  schedule:
    - cron: '23 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python .github/scripts/webcam_scraper.py

      - name: Configure Git
        run: |
          git config --local user.email "hletrd@users.noreply.github.com"
          git config --local user.name "hletrd-bot"

      - name: Commit changes
        run: |
          git add links.json sitemap.xml videos+ld.json
          git diff --quiet && git diff --staged --quiet || git commit -m "[Bot] Update webcam links"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}